import React, { createContext, useContext, useState, useEffect } from "react";
import { supabase } from "../lib/supabase";

const AuthContext = createContext();

export function useAuth() {
    return useContext(AuthContext);
}

export function AuthProvider({ children }) {
    const [user, setUser] = useState(null);
    const [session, setSession] = useState(null);
    const [loading, setLoading] = useState(true);

    async function signup(email, password, username, type = 'individual') {
        try {
            // 1. Sign up with Supabase Auth
            const { data, error } = await supabase.auth.signUp({
                email,
                password,
                options: {
                    data: {
                        username,
                        type
                    }
                }
            });

            if (error) {
                console.error("Supabase SignUp Error:", error);
                throw error;
            }

            if (data.user) {
                // 2. Insert into public.users table as requested
                // Note: The schema defines 'id' as bigint generated by default. 
                // We cannot force the UUID from auth into a bigint column unless the schema changes.
                // Assuming we treat them independently but linked by email for now, 
                // OR we just insert the profile data.
                // Given the instruction "integrate the users table only", we will attempt an insert.

                const { error: dbError } = await supabase
                    .from('users')
                    .insert([
                        {
                            username,
                            email,
                            password: 'MANAGED_BY_SUPABASE', // Placeholder as we shouldn't store plain text
                            "typeIndividual": type === 'individual'
                        }
                    ]);

                if (dbError) {
                    console.error("Database Insert Error:", dbError);
                    // We don't throw here to avoid blocking the auth flow if only the profile fails,
                    // but it depends on strictness. We'll log it.
                }
            }

            return data;
        } catch (err) {
            console.error(err);
            throw err;
        }
    }

    async function login(email, password) {
        try {
            const { data, error } = await supabase.auth.signInWithPassword({
                email,
                password
            });

            if (error) {
                console.error("Supabase Login Error:", error);
                throw error;
            }

            return data;
        } catch (err) {
            console.error(err);
            throw err;
        }
    }

    async function logout() {
        try {
            const { error } = await supabase.auth.signOut();
            if (error) {
                console.error("Supabase Logout Error:", error);
                throw error;
            }
        } catch (err) {
            console.error(err);
            throw err;
        }
    }

    async function updateUserProfile(updates) {
        try {
            // 1. Update Supabase Auth User Metadata (for app-wide availability)
            const { data: authData, error: authError } = await supabase.auth.updateUser({
                data: updates
            });

            if (authError) throw authError;

            // 2. Update Public Users Table (for persistence/social features)
            if (user?.email) {
                const { error: dbError } = await supabase
                    .from('users')
                    .update(updates)
                    .eq('email', user.email);

                if (dbError) {
                    console.error("Values not synced to public.users:", dbError);
                    // Non-blocking, as Auth metadata is primary for this session
                }
            }

            // Update local state immediately for UI responsiveness
            setUser(prev => ({ ...prev, user_metadata: { ...prev.user_metadata, ...updates } }));

            return authData;
        } catch (error) {
            console.error("Error updating profile:", error);
            throw error;
        }
    }

    // Initialize session
    useEffect(() => {
        supabase.auth.getSession().then(({ data: { session } }) => {
            setSession(session);
            setUser(session?.user ?? null);
            setLoading(false);
        });

        const { data: { subscription } } = supabase.auth.onAuthStateChange(async (_event, session) => {
            setSession(session);

            if (session?.user) {
                // Optionally fetch extended profile from public.users
                // const { data: profile } = await supabase.from('users').select('*').eq('email', session.user.email).single();
                // setUser({ ...session.user, ...profile });
                setUser(session.user);
            } else {
                setUser(null);
            }

            setLoading(false);
        });

        return () => subscription.unsubscribe();
    }, []);

    const value = {
        user,
        session,
        signup,
        login,
        logout,
        updateUserProfile,
        loading
    };

    return (
        <AuthContext.Provider value={value}>
            {!loading && children}
        </AuthContext.Provider>
    );
}
